version: '3.7'

services:
  quadrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    environment:
      - QDRANT_LOG_LEVEL=INFO

volumes:
  qdrant-data:
    driver: local